### ISSUE TITLE
AS7262 6 channels calibration

### ISSUE THREAD

**Issue by hugzerdizer** [adafruit/Adafruit_AS726x#11]
Hello there,

I'm pretty new in coding and in github. I need help for a project. I'm working on a ESP32 D32 using Arduino IDE to run a sensor: AS7262x from Adafruit. I guess that to use the sensor correctly we need to calibrate it. But I can't find a explained solution for this. I read some codes but I can't understand the steps that they used. I know that there is function like "readCalibratedViolet()" but I don't undersatnd if this function is reading pre-set values or values that we measured. My idea is basicaly to calibrate the sensor by placing a led in front and to "say" this is blue or green ect... for the 6 channels. Can someone help me on it ? The library for the sensor is called "Adafruit_AS726x.h"

Thanks.

Hugo.

**Comment by caternuson** [comment]
Opening an issue thread here is done when there is a demonstrable issue with using the library code. For general support and application specific questions, will want to ask elsewhere. Can try the Adafruit forums:
https://forums.adafruit.com/
or discord:
http://adafru.it/discord
to see if maybe someone else has dealt with this.

Or any other similar tech forum.

Unfortunately, the AS7262 datasheet does not provide much information about specifically how the calibrated values are derived from the raw values:
https://ams.com/en/as7262
