### ISSUE TITLE
AS7262 Interrupts not working?

### ISSUE THREAD

**Issue by astrorafael** [adafruit/Adafruit_AS726x#2]
Hi

I'm trying to use interrupts for the AS7262 breakout board you've designed. I've read the datasheet, tried several ways. However, the INT pin doesn't "move". 

Last test I did was to disconnect the AS7262 INT pin output from the Arduino EXT0 input and attached an oscilloscope to verify that the levels were not moving and apparently that was the case.

I was wondering if you have verified at some point that the INT pin does change levels. I have thought that maybe the AS7262 firmware is not allowing interrupts either on purpose or because of a bug.

Best wishes
Rafael

**Comment by ladyada** [comment]
hiya we did not get INT pin to do anything, maybe its for UART mode only? or maybe there's a firmware bug. we don't have any info other than the datasheet :)

**Comment by astrorafael** [comment]
Good to know. :-) Thank you very much for your response.
I don't see anywhere in the AMS website a reference to this firmware, not even how to download it.
