### ISSUE TITLE
Driver for STM32H743ZI

### ISSUE THREAD

**Issue by sourabhmisal** [adafruit/Adafruit_AS726x#6]
Is there an AS7262 driver software for STM32H743ZI ? I am trying to interface the sensor using I2C HAL library of STM32H743ZI but I am not able to read the register values from the sensor, as mentioned in sensor's datasheet. Could you help me out?

I have tried out a sample code mentioned in the datasheet, but I was not able to read the values
Code:

 
    uint8_t i2cm_AS7262_read(uint16_t virtualReg){
    HAL_StatusTypeDef ret = HAL_OK;
    volatile uint8_t status , d;
    
    while(1)
    {
    
    ret = HAL_I2C_Mem_Read(&hi2c1, (AS7262_ADDR << 1) | 0x01, I2C_AS7262_SLAVE_STATUS_REG, I2C_MEMADD_SIZE_8BIT, &status, 1, 500);
    if (ret != HAL_OK) {
	    return ret;
    }
    if (status == I2C_AS7262_SLAVE_TX_VALID) {
	    break;
    }
    }
    
    ret = HAL_I2C_Mem_Write(&hi2c1, (AS7262_ADDR << 1)  , I2C_AS7262_SLAVE_WRITE_REG, I2C_MEMADD_SIZE_8BIT, (uint8_t)(virtualReg), 1, 500);
    
    while(1)
    {
    ret = HAL_I2C_Mem_Read(&hi2c1, (AS7262_ADDR << 1) | 0x01, I2C_AS7262_SLAVE_STATUS_REG, I2C_MEMADD_SIZE_8BIT, &status, 1, 500);
    if (ret != HAL_OK) {
	    return ret ;
    }
    if ((status & I2C_AS7262_SLAVE_RX_VALID) != 0) {
	    break;
    }
    }
    
    HAL_I2C_Mem_Read(&hi2c1, (AS7262_ADDR << 1) | 0x01, I2C_AS7262_SLAVE_READ_REG, I2C_MEMADD_SIZE_8BIT, &d, 1, 500);
    return d;
    
    }

**Comment by ladyada** [comment]
there is not
